config/routes.rb
Rails.application.routes.draw do

  devise_for :institutions, path: 'institutions', controllers: {
    passwords:     'institutions/passwords',
    registrations: 'institutions/registrations',
    sessions:      'institutions/sessions',
  }

  resource :institution, only: [:show] do
    resources :seekers
  end

  devise_for :companies, path: 'companies', controllers: {
    passwords:     'companies/passwords',
    registrations: 'companies/registrations',
    sessions:      'companies/sessions',
  }

  resource :company, only: [:show]

  resources :companies do
    resources :jobs, only: [:show, :index]
  end

  resources :jobs

  root to: 'pages#index'
end

app/models/institution.rb
class Institution < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :seekers
end

app/controllers/institutions/passwords_controller.rb
class Institutions::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/institutions/registrations_controller.rb
class Institutions::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/institutions/sessions_controller.rb
class Institutions::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :require_institution
end

app/views/institutions/show.html.erb
<% content_for :title do  %>
    <h1 class="ui header">
        <%= current_institution.name %>
        <div class="sub header">
            Institution profile and job seeker listing
        </div>
    </h1>
<% end %>

<div class="ui grid">
    <div class="ui four wide column">
        <div class="ui segment">
            <h2>Institution info</h2>
            <p><%= current_institution.name %></p>
            <p>Email: <%= current_institution.email %></p>
            <p><%= link_to 'Edit information', edit_institution_registration_path, class: 'ui button' %></p>
        </div>
    </div>



    <div class="ui twelve wide column">
        <div class="ui segment">
            <h2>Job seekers</h2>
            <% if current_institution.seekers.empty? %>
                <p>
                    No seekers at the moment.
                </p>
            <% else %>
                <% current_institution.seekers.each do |seeker| %>
                    <div class="ui fluid card">
                        <div class="content">
                            <div class="header"><%= link_to seeker.name, institution_seeker_path(seeker) %></div>
                            <div class="meta">Created <%= time_ago_in_words seeker.created_at %> ago</div>
                            <div class="description">
                                <p>Languages:
                                    <% seeker.language_list.each do |l| %>
                                        <a class="ui red label"><%= l %></a>
                                    <% end %>
                                </p>

                                <p>Skills:
                                    <% seeker.skill_list.each do |s| %>
                                        <a class="ui blue label"><%= s %></a>
                                    <% end %>
                                </p>
                            </div>
                        </div>
                        <div class="extra content">
                            <span class="left floated">
                                <i class="phone icon"></i>
                                <%= seeker.phone %>
                            </span>
                            <span class="right floated">
                                <i class="map icon"></i>
                                <%= seeker.city %>
                            </span>
                        </div>
                    </div>
                <% end %>
            <% end %>
            <%= link_to 'Register a job seeker', new_institution_seeker_path, class: 'ui button primary' %>
        </div>
    </div>
</div>