config/routes.rb
Rails.application.routes.draw do

  devise_for :institutions, path: 'institutions', controllers: {
    passwords:     'institutions/passwords',
    registrations: 'institutions/registrations',
    sessions:      'institutions/sessions',
  }

  resource :institution, only: [:show] do
    resources :seekers
  end

  devise_for :companies, path: 'companies', controllers: {
    passwords:     'companies/passwords',
    registrations: 'companies/registrations',
    sessions:      'companies/sessions',
  }

  resource :company, only: [:show]

  resources :companies do
    resources :jobs, only: [:show, :index]
  end

  resources :jobs

  root to: 'pages#index'
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company

  acts_as_taggable_on :skills, :languages

  def at_least_one_match_for_institution(institution)
    @at_least_one_match_for_institution ||=
      institution.seekers.select do |seeker|
        (language_list & seeker.language_list).any? || (skill_list & seeker.skill_list).any? || skill_list.empty? && language_list.empty?
      end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
    @jobs = @jobs.tagged_with(params[:language]) if params[:language]
    @jobs = @jobs.tagged_with(params[:skill]) if params[:skill]
    @jobs = @jobs.where(company_id: params[:company_id]) if params[:company_id]
  end

  def new
    @job = current_company.jobs.build
  end

  def create
    @job = current_company.jobs.build(jobs_params)
    if @job.save
      redirect_to @job
    else
      render :new
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    @job = current_company.jobs.find(params[:id])
  end

  def update
    @job = current_company.jobs.find(params[:id])
    @job.update!(jobs_params)
    redirect_to @job
  end

  private

  def jobs_params
    params.require(:job).permit(:title, :description, :country, :city,
      :language_list, :skill_list)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def any_filters_applied?
    params[:company_id] || params[:language] || params[:skill]
  end
end

app/views/jobs/_form.html.erb
<div class="ui container segment fluid">
    <%= form_for @job, html: {class: 'ui large form'} do |f| %>
        <div class="field">
            <%= f.label      :title %><br />
            <%= f.text_field :title, autofocus: true %>
        </div>

        <div class="field">
            <%= f.label     :description %><br />
            <%= f.text_area :description %>
        </div>

        <div class="field">
            <%= f.label      :country %><br />
            <%= f.text_field :country, value: 'Portugal' %>
        </div>

        <div class="field">
            <%= f.label      :city %><br />
            <%= f.text_field :city, value: 'Lisbon' %>
        </div>

        <div class="field">
            <%= f.label      :language_list %><br />
            <%= f.text_field :language_list, value: f.object.language_list.to_s,
              class: 'autocomplete', autocomplete: 'off',
              data: { list: all_languages, minchars: 1 } %>
        </div>

        <div class="field">
            <%= f.label      :skill_list %><br />
            <%= f.text_field :skill_list, value: f.object.skill_list.to_s,
              class: 'autocomplete', autocomplete: 'off',
              data: { list: all_skills, minchars: 1 } %>
        </div>

        <%= f.submit "Add job", class: 'ui primary button' %>
        <a href="<%= company_path %>" class="ui button">Cancel</a>
    <% end %>
</div>

app/views/jobs/edit.html.erb
<h2>Edit <%= @job.title %></h2>

<%= render 'form' %>

app/views/jobs/index.html.erb
<% content_for :title do  %>
    <h1 class="ui header">
        All jobs
        <div class="sub header">
            All available job postings
        </div>
    </h1>
<% end %>

<div class="ui container segment">
    <%= link_to 'Clear filters', jobs_path, class: 'ui button' if any_filters_applied? %>

    <% @jobs.each do |job| %>
        <div class="ui fluid card">
            <div class="content">
                <div class="header"><%= link_to job.title, job %></div>
                <div class="meta">
                    <%= link_to job.company.name, request.query_parameters.merge(company_id: job.company_id) %>
                </div>
                <div class="description">
                    <%= job.description %>
                </div>
            </div>
            <div class="extra content">
                <span class="left floated">
                    <i class="check icon"></i>
                    <%= rand(250) %> Vacancies
                </span>
                <span style="margin-left: 1em;" class="right floated">
                    <i class="map icon"></i>
                    <%= job.city %>
                </span>

                <span style="margin-left: 1em;" class="right floated">
                    <i class="write icon"></i>
                    <% job.language_list.each do |l| %>
                        <%= link_to l, request.query_parameters.merge(language: l), class: 'tag' %>
                    <% end %>
                </span>

                <span class="right floated">
                    <i class="write icon"></i>
                    <% job.skill_list.each do |s| %>
                        <%= link_to s, request.query_parameters.merge(skill: s), class: 'tag' %>
                    <% end %>
                </span>
            </div>
        </div>
    <% end %>
</div>

app/views/jobs/new.html.erb
<% content_for :title do  %>
    <h1 class="ui header">
        New Job at <%= current_company.name %>
        <div class="sub header">
            Create a new job posting
        </div>
    </h1>
<% end %>

<%= render 'form' %>

app/views/jobs/show.html.erb
<% content_for :title do  %>
    <h1 class="ui header">
        <%= @job.title %> at <%= @job.company.name %>
        <div class="sub header">
            View job details and possible matches
        </div>
    </h1>
<% end %>

<div class="ui container segment">
    <h2>Details</h2>
    <p><%= @job.city %>, <%= @job.country %></p>
    <p><%= @job.description %></p>
    <p>Posted <%= time_ago_in_words @job.created_at %></p>
    <p>
        Languages:
        <% @job.language_list.each do |lang| %>
            <span class="ui label red"><%= lang %></span>
        <% end %>
    </p>
    <p>
        Skills: <% @job.skill_list.each do |skill| %>
        <span class="ui label blue"><%= skill %></span>
        <% end %>
    </p>

    <%= link_to "Edit details", edit_job_path, class: 'ui button' %>
    <%= link_to "All jobs by #{@job.company.name}", company_jobs_path(@job.company), class: 'ui button' %>
    <%= link_to "All jobs", jobs_path, class: 'ui button' %>

</div>

<% if institution_signed_in? && @job.at_least_one_match_for_institution(current_institution) %>
    <div class="ui container segment">
        <h2>Matching Candidates</h2>
        <p>Presented candidates match on skills and language. If none are defined, all candidates are elegible.</p>
        <% @job.at_least_one_match_for_institution(current_institution).each do |seeker| %>
            <div class="ui fluid card">
                <div class="content">
                    <div class="header"><%= link_to seeker.name, institution_seeker_path(seeker) %></div>
                    <div class="meta">Created <%= time_ago_in_words seeker.created_at %> ago</div>
                    <div class="description">
                        <p>Languages:
                            <% seeker.language_list.each do |l| %>
                                <a class="ui red label"><%= l %></a>
                            <% end %>
                        </p>

                        <p>Skills:
                            <% seeker.skill_list.each do |s| %>
                                <a class="ui blue label"><%= s %></a>
                            <% end %>
                        </p>
                    </div>
                </div>
                <div class="extra content">
                    <span class="left floated">
                        <i class="phone icon"></i>
                        <%= seeker.phone %>
                    </span>
                    <span class="right floated">
                        <i class="map icon"></i>
                        <%= seeker.city %>
                    </span>
                </div>
            </div>
        <% end %>
    </div>
<% end %>