config/routes.rb
Rails.application.routes.draw do

  devise_for :institutions, path: 'institutions', controllers: {
    passwords:     'institutions/passwords',
    registrations: 'institutions/registrations',
    sessions:      'institutions/sessions',
  }

  resource :institution, only: [:show] do
    resources :seekers
  end

  devise_for :companies, path: 'companies', controllers: {
    passwords:     'companies/passwords',
    registrations: 'companies/registrations',
    sessions:      'companies/sessions',
  }

  resource :company, only: [:show]

  resources :companies do
    resources :jobs, only: [:show, :index]
  end

  resources :jobs

  root to: 'pages#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Jobs For Good</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <style type="text/css">
         body {
             background-color: #DADADA;
         }
         .ui.menu .item img.logo {
             margin-right: 1.5em;
         }
         .main.container {
             <% if content_for? :title %>
             margin-top: 2em;
             <% else %>
             margin-top: 7em;
             <% end %>
         }
         .title.container {
             margin-top: 3em;
             background-color: #FFFFFF;
             padding: 2em 0;
         }
         .wireframe {
             margin-top: 2em;
         }
         .ui.footer.segment {
             margin: 5em 0em 0em;
             padding: 5em 0em;
         }
        </style>
    </head>

    <body>

        <div class="ui fixed inverted menu">
            <div class="ui container">
                <a href="/jobs" class="header item">
                    Jobs for Good
                </a>
                <% if institution_signed_in? %>
                  <%= link_to current_institution.name, institution_path, class: 'item' %>
                  <%= link_to 'Add Job Seeker', new_institution_seeker_path, class: 'item' %>
                <% elsif company_signed_in? %>
                  <%= link_to current_company.name, company_path, class: 'item' %>
                  <%= link_to 'Add Job', new_job_path, class: 'item' %>
                <% end %>
                <div class="right item">
                  <% if signed_in? %>
                    <%= link_to 'Sign Out', sign_out_path, method: :delete %> <br>
                  <% else %>
                    <a href="<%= new_institution_session_path %>" class="ui inverted button">Institutions Sign In</a>
                    <a href="<%= new_company_session_path %>" class="ui inverted button" style="margin-left: 0.5em;">Companies Sign In</a>
                  <% end %>
                </div>
            </div>
        </div>

        <div class="ui fluid container">
            <% if content_for? :title %>
            <div class="ui title fluid container">
                <div class="ui container">
                    <%= yield :title %>
                </div>
            </div>
            <% end %>

            <div class="ui main container">
                <% if notice %>
                    <div class="ui info message">
                        <i class="close icon"></i>
                        <div class="header">
                            <%= notice %>
                        </div>
                    </div>
                <% end %>

                <% if alert %>
                    <div class="ui negative message">
                        <i class="close icon"></i>
                        <div class="header">
                            <%= alert %>
                        </div>
                    </div>
                <% end %>

                <%= yield %>
            </div>
        </div>

        <div class="ui inverted vertical footer segment">
            <div class="ui center aligned container">
                <div class="ui horizontal inverted small divided link list">
                    <a class="item" href="#">Site Map</a>
                    <a class="item" href="#">Contact Us</a>
                    <a class="item" href="#">Terms and Conditions</a>
                    <a class="item" href="#">Privacy Policy</a>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/layouts/hero.html.erb
<!DOCTYPE html>
<html>
    <head>
        <!-- Standard Meta -->
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

        <!-- Site Properties -->
        <title>Jobs for Good</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <style type="text/css">

         .hidden.menu {
             display: none;
         }

         .masthead.segment {
             min-height: 700px;
             padding: 1em 0em;
         }
         .masthead .logo.item img {
             margin-right: 1em;
         }
         .masthead .ui.menu .ui.button {
             margin-left: 0.5em;
         }
         .masthead h1.ui.header {
             margin-top: 3em;
             margin-bottom: 0em;
             font-size: 4em;
             font-weight: normal;
         }
         .masthead h2 {
             font-size: 1.7em;
             font-weight: normal;
         }

         .ui.vertical.stripe {
             padding: 8em 0em;
         }
         .ui.vertical.stripe h3 {
             font-size: 2em;
         }
         .ui.vertical.stripe .button + h3,
         .ui.vertical.stripe p + h3 {
             margin-top: 3em;
         }
         .ui.vertical.stripe .floated.image {
             clear: both;
         }
         .ui.vertical.stripe p {
             font-size: 1.33em;
         }
         .ui.vertical.stripe .horizontal.divider {
             margin: 3em 0em;
         }

         .quote.stripe.segment {
             padding: 0em;
         }
         .quote.stripe.segment .grid .column {
             padding-top: 5em;
             padding-bottom: 5em;
         }

         .footer.segment {
             padding: 5em 0em;
         }

         .secondary.pointing.menu .toc.item {
             display: none;
         }

         @media only screen and (max-width: 700px) {
             .ui.fixed.menu {
                 display: none !important;
             }
             .secondary.pointing.menu .item,
             .secondary.pointing.menu .menu {
                 display: none;
             }
             .secondary.pointing.menu .toc.item {
                 display: block;
             }
             .masthead.segment {
                 min-height: 350px;
             }
             .masthead h1.ui.header {
                 font-size: 2em;
                 margin-top: 1.5em;
             }
             .masthead h2 {
                 margin-top: 0.5em;
                 font-size: 1.5em;
             }
         }


        </style>

        <script src="assets/library/jquery.min.js"></script>
        <script src="../dist/components/visibility.js"></script>
        <script src="../dist/components/sidebar.js"></script>
        <script src="../dist/components/transition.js"></script>
        <script>
         $(document)
             .ready(function() {

                 // fix menu when passed
                 $('.masthead')
                     .visibility({
                         once: false,
                         onBottomPassed: function() {
                             $('.fixed.menu').transition('fade in');
                         },
                         onBottomPassedReverse: function() {
                             $('.fixed.menu').transition('fade out');
                         }
                     })
                 ;

                 // create sidebar and attach to menu open
                 $('.ui.sidebar')
                     .sidebar('attach events', '.toc.item')
                 ;

             })
         ;
        </script>
    </head>
    <body>
        <!-- Page Contents -->
        <div class="pusher">
            <div class="ui inverted vertical masthead center aligned segment">

                <div class="ui container">
                    <div class="ui large secondary inverted pointing menu">
                        <a class="toc item">
                            <i class="sidebar icon"></i>
                        </a>
                        <a href="/" class="active item">Home</a>
                        <div class="right item">
                            <a href="<%= new_institution_session_path %>" class="ui inverted button">Institutions Sign In</a>
                            <a href="<%= new_company_session_path %>" class="ui inverted button" style="margin-left: 0.5em;">Companies Sign In</a>
                        </div>
                    </div>
                </div>

                <% if notice %>
                    <div class="ui info message">
                        <i class="close icon"></i>
                        <div class="header">
                            <%= notice %>
                        </div>
                    </div>
                <% end %>

                <% if alert %>
                    <div class="ui negative message">
                        <i class="close icon"></i>
                        <div class="header">
                            <%= alert %>
                        </div>
                    </div>
                <% end %>

                <div class="ui text container">
                    <h1 class="ui inverted header">
                        Jobs for Good
                    </h1>
                    <h2>Reach out to thousands of migrants. Post your job today.</h2>
                    <a href="<%= new_company_session_path %>"><div class="ui huge primary button">Get Started <i class="right arrow icon"></i></div></a>
                </div>

            </div>

            <div class="ui vertical stripe segment">
                <div class="ui middle aligned stackable grid container">
                    <div class="row">
                        <div class="eight wide column">
                            <h3 class="ui header">We connect migrants with job offers</h3>
                            <p>We work with national resettlement agencies to connect job offers to thousands of migrants.</p>
                            <h3 class="ui header">We help migrants get back on their feet</h3>
                            <p>By shortening the distance between job offers and skilled migrants we help everyone, be it aiding migrants to reintegrate into society or companies looking for skilled collaboration.</p>
                        </div>
                        <div class="six wide right floated column">
                            <img src="http://images.goodfood.com.au/2011/08/21/2572183/festival-for-refugees_wide-420x0.jpg" class="ui large bordered rounded image">
                        </div>
                    </div>
                </div>
            </div>

            <div class="ui inverted vertical footer segment">
                <div class="ui container">
                    <div class="ui stackable inverted divided equal height stackable grid">
                        <div class="three wide column">
                            <h4 class="ui inverted header">About</h4>
                            <div class="ui inverted link list">
                                <a href="#" class="item">Sitemap</a>
                                <a href="#" class="item">Contact Us</a>
                                <a href="#" class="item">Religious Ceremonies</a>
                                <a href="#" class="item">Gazebo Plans</a>
                            </div>
                        </div>
                        <div class="three wide column">
                            <h4 class="ui inverted header">Services</h4>
                            <div class="ui inverted link list">
                                <a href="#" class="item">Banana Pre-Order</a>
                                <a href="#" class="item">DNA FAQ</a>
                                <a href="#" class="item">How To Access</a>
                                <a href="#" class="item">Favorite X-Men</a>
                            </div>
                        </div>
                        <div class="seven wide column">
                            <h4 class="ui inverted header">Footer Header</h4>
                            <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>